name: your_food
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0

  #For notification & background Service
  intl: ^0.18.1
  flutter_local_notifications: ^15.1.1
  rxdart: ^0.27.7
  android_alarm_manager_plus: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  color: "#FF0000"
  image: assets/your_food.png
  color_dark: "#042a49"
  image_dark: assets/your_food.png

  android_12:
    image: assets/your_food.png
    color: "#FF0000"
    color_dark: "#042a49"
    image_dark: assets/your_food.png

flutter:
  uses-material-design: true
  assets:
    - assets/