// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzzukeg9N8b1mU1o-Rutrpxg639ulciFQ',
    appId: '1:838912348363:web:ceb060f4e9984a67010b4e',
    messagingSenderId: '838912348363',
    projectId: 'your-food-01',
    authDomain: 'your-food-01.firebaseapp.com',
    storageBucket: 'your-food-01.appspot.com',
    measurementId: 'G-SJXV2D2ES5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2zpYLWJM8dgOFa-E5xR2nGfXr_WuKI6E',
    appId: '1:838912348363:android:53bbef896f511d0c010b4e',
    messagingSenderId: '838912348363',
    projectId: 'your-food-01',
    storageBucket: 'your-food-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmB2n_RgY8a3Kwvl4BQZcM-R1tJHH_GO4',
    appId: '1:838912348363:ios:50a17f65707ebc58010b4e',
    messagingSenderId: '838912348363',
    projectId: 'your-food-01',
    storageBucket: 'your-food-01.appspot.com',
    iosBundleId: 'com.food.yourFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmB2n_RgY8a3Kwvl4BQZcM-R1tJHH_GO4',
    appId: '1:838912348363:ios:1e9f7b170841088f010b4e',
    messagingSenderId: '838912348363',
    projectId: 'your-food-01',
    storageBucket: 'your-food-01.appspot.com',
    iosBundleId: 'com.food.yourFood.RunnerTests',
  );
}
